version: '3'
services:
  app-frontend:
    build: ./frontend/.docker
    entrypoint: ./.docker/entrypoint.sh
    container_name: your-destination-app-frontend
    ports:
      - '3001:3001'
    volumes:
      - './frontend:/home/node/app'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  app-backend:
    build: ./backend/.docker
    entrypoint: ./.docker/entrypoint.sh
    container_name: your-destination-app-backend
    ports:
      - '3000:3000'
    volumes:
      - './backend:/home/node/app'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db

  db:
    build: ./backend/.docker/postgres
    container_name: your-destination-api-db
    restart: always
    tty: true
    volumes:
      - './backend/.docker/dbdata:/var/lib/postgresql/data'
      - './backend/.docker/postgres:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=your_destination
      - FILE_DATA_POSTGRES=/.docker/postgres/init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: your-destination-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    depends_on:
      - db
